name: PanelCraft
version: ${project.version}
main: net.kunmc.lab.panelcraft.PanelCraft
api-version: 1.15
authors: [ YukiAt ]

commands:
  panel:
    permission: panelcraft.panel

permissions:
  panelcraft.panel:
    default: op
